# Generated by Django 6.0.1 on 2026-05-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarday',
            name='status',
            field=models.CharField(choices=[('none', 'No status'), ('done', 'Completed'), ('cancel', 'Cancelled')], default='none', max_length=10),
        ),
    ]
