# Generated by Django 6.0.1 on 2026-05-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_publiccomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publiccomment',
            options={'ordering': ['-is_pinned', '-pinned_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='publiccomment',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publiccomment',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
